### ISSUE TITLE
cloud.ca driver not visible if not using github authentication

### ISSUE THREAD

**Issue by pdion891** [cloud-ca/ui-driver-cloudca#5]
The cloud.ca driver is not visible in adding host section in following Access Control scenarios:
- no authentication (initial setup)
- Local Authentication

It only seams to be usable when using github authentication.

**Comment by prollynomial** [comment]
When we were developing the driver we were using a Rancher setup with no auth and it worked fine - can you provide the steps to reproduce?

**Comment by simongodard** [comment]
I also tried with local authentication and it works. I will test with the latest Rancher (1.4.1) to see if it makes a difference.

**Comment by simongodard** [comment]
I couldn't reproduce the problem on 1.4.1.
![image](https://cloud.githubusercontent.com/assets/6817637/23169352/6a05c184-f819-11e6-8f58-4f867d5f7fe5.png)

Will close until we can find steps to reproduce.
