### ISSUE TITLE
Add hosted download link for Rancher UI

### ISSUE THREAD

**Issue by swill** [cloud-ca/ui-driver-cloudca#6]
In the v0.1.0 version you specify the following url for download:
https://objects-qc.cloud.ca/v1/5ef827605f884961b94881e928e7a250/rancher-ui-driver/v0.1.0/component.js

Ideally the v1.0.0 release would have a note in the release notes to give the v1.0.0 download link:
https://objects-qc.cloud.ca/v1/5ef827605f884961b94881e928e7a250/rancher-ui-driver/v1.0.0/component.js

**Comment by prollynomial** [comment]
Good call, done - [https://github.com/cloud-ca/ui-driver-cloudca/releases/tag/v1.0.0](https://github.com/cloud-ca/ui-driver-cloudca/releases/tag/v1.0.0)
